apiVersion: v1
kind: Service
metadata:
  name: vcluster-nodeport
  namespace: virtualclusters
spec:
  selector:
    app: vcluster
    release: <Release Name>
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort